plugins {
    id 'io.github.jigga.helm'
    id 'io.github.jigga.helm-publish'
}

helm {
    charts {
        main {

        }
    }
    publishing {
        repositories {
            artifactory  {
                url = uri("http://localhost:$serverPort/artifactory/folder1/folder2")

                credentials {
                    username = 'testUserName'
                    password = 'testPassword'
                }
            }
        }
    }
}
